// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ranking.Data;

#nullable disable

namespace Ranking.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ranking.Models.PointConfig", b =>
                {
                    b.Property<long>("ConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConfigID"));

                    b.Property<int>("PointPerMonth")
                        .HasColumnType("int");

                    b.Property<int>("PointPerRM")
                        .HasColumnType("int");

                    b.HasKey("ConfigID");

                    b.ToTable("PointConfig");
                });

            modelBuilder.Entity("Ranking.Models.Tier", b =>
                {
                    b.Property<long>("TierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TierID"));

                    b.Property<decimal>("TierMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TierMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TierID");

                    b.ToTable("Tier");
                });
#pragma warning restore 612, 618
        }
    }
}
